apiVersion: v1
kind: Namespace
metadata:
  name: jmx-perms
---
apiVersion: v1
kind: Secret
metadata:
  namespace: jmx-perms
  name: jmx-secret
data:
  jmxremote.password: bW9uaXRvclJvbGUgIHF1aXRlc2VjcmV0CmNvbnRyb2xSb2xlICB2M3J5UzNrciF0Cg==
---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: jmx-perms
  name: jmx-config
data:
  jmxremote.access: |
    monitorRole   readonly
    controlRole   readwrite
---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: with-root
  name: with-root
  namespace: jmx-perms
spec:
  replicas: 1
  selector:
    matchLabels:
      app: with-root
  template:
    metadata:
      labels:
        app: with-root
    spec:
      containers:
        - image: willthames/jmx-demo
          name: jmx-demo
          args:
            - -Dcom.sun.management.jmxremote.port=9090
            - -Dcom.sun.management.jmxremote.rmi.port=9091
            - -Dcom.sun.management.jmxremote.ssl=false
            - -Dcom.sun.management.jmxremote.password.file=/java/jmxremote.password
            - -Dcom.sun.management.jmxremote.access.file=/java/jmxremote.access
            - -Djava.rmi.server.hostname=localhost
            - Sleep
            - "10000"
          volumeMounts:
            - name: password
              mountPath: /java/jmxremote.password
              subPath: jmxremote.password
            - name: access
              mountPath: /java/jmxremote.access
              subPath: jmxremote.access
      volumes:
        - name: password
          secret:
            secretName: jmx-secret
            defaultMode: 0600
        - name: access
          configMap:
            name: jmx-config
